development:
  adapter: "postgresql"
  host: "localhost"
  database: "development"
  encoding: "utf8"

test:
  adapter: "sqlite3"
  database: sqlite3:db/test.db
  pool: 5
  timeout: 5000

production:
  adapter: sqlite3
  database: db/production.db
  pool: 5
  timeout: 5000
